---
# tasks file for ansible-windows-iis

- import_tasks: set_facts.yml
  when: windows_iis_role is defined

- import_tasks: features.yml
  when: windows_iis_role is defined

- import_tasks: websites.yml
  when: >
        windows_iis_role is defined and
        windows_iis_websites is defined and
        windows_iis_web_server

- import_tasks: reboot.yml
  when: windows_iis_role is defined
